server:
  port: 8181
  contextPath: /uaa
security:
  user:
    password: password
  enable-csrf: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: root
    password: admin
    initialize: true
security.ignored: /resources/**
eureka:
  instance:
     hostname: user-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
